name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - uses: ruby/setup-ruby@97ecb7b512899eb71ab1bf2310a624c6f1589ac6 # v1.308.0
        with:
          bundler-cache: true

      - name: RuboCop
        run: bundle exec rubocop -f github

  rspec:
    runs-on: ubuntu-latest
    needs: rubocop
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - uses: ruby/setup-ruby@97ecb7b512899eb71ab1bf2310a624c6f1589ac6 # v1.308.0
        with:
          bundler-cache: true

      - name: DB setup
        env:
          RAILS_ENV: test
        run: bundle exec rails db:test:prepare

      - name: RSpec
        env:
          RAILS_ENV: test
        run: bundle exec rspec
