name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - uses: ruby/setup-ruby@afeafc3d1ab54a631816aba4c914a0081c12ff2f # v1.310.0
        with:
          bundler-cache: true

      - name: RuboCop
        run: bundle exec rubocop -f github

  brakeman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - uses: ruby/setup-ruby@afeafc3d1ab54a631816aba4c914a0081c12ff2f # v1.310.0
        with:
          bundler-cache: true

      - name: Brakeman
        run: bundle exec brakeman -q

  bundler-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - uses: ruby/setup-ruby@afeafc3d1ab54a631816aba4c914a0081c12ff2f # v1.310.0
        with:
          bundler-cache: true

      - name: Bundler Audit
        run: bundle exec bundler-audit

  rspec:
    runs-on: ubuntu-latest
    needs: rubocop
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - uses: ruby/setup-ruby@afeafc3d1ab54a631816aba4c914a0081c12ff2f # v1.310.0
        with:
          bundler-cache: true

      - name: DB setup
        env:
          RAILS_ENV: test
        run: bundle exec rails db:test:prepare

      - name: RSpec
        env:
          RAILS_ENV: test
        run: bundle exec rspec
